F811 redefinition of unused
- DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/alpha/switching/test_trunk_port.py:10:1: F811 redefinition of unused 'tgen_utils_get_loss' from line 10
- DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py:9:1: F811 redefinition of unused 'Files' from line 7

Signed-off-by: Mircea Dan <mircea-dan.gheorghe@keysight.com>